### ISSUE TITLE
[PE-D][Tester A] Not clear on the approaching expenses at the start

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-3/tp#102]
Consider adding more details on the "Approaching expenses: " to make it clear to the users. Currently I am not sure the duration of the approaching expenses to the current day, is it a week, a month. This part is also not really specified in the user guide. This perhaps could be implemented into a feature

![image.png](https://raw.githubusercontent.com/RuiShengGit/ped/main/files/05b1e457-b76b-42ec-8dc9-97c8d512cf30.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RuiShengGit/ped#9

**Comment by Toh-HongFeng** [comment]
add Reminders to UG
