### ISSUE TITLE
[PE-D][Tester B] UG Bug_Quick Start

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-3/tp#64]
Missing command under point 4

![image.png](https://raw.githubusercontent.com/jingyaaa/ped/main/files/7eba37d5-a73c-42a6-ab24-569f95a98c3a.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jingyaaa/ped#1

**Comment by alexgoexercise** [comment]
Fixed by Alex
