### ISSUE TITLE
[PE-D][Tester A] FAQ in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-3/tp#70]
I think the team should consider removing this question from the User Guide since the question and answer does not seem to be addressing questions on the product.

![image.png](https://raw.githubusercontent.com/RuiShengGit/ped/main/files/f6fc1168-003a-423f-8181-a1ac21a593f6.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: RuiShengGit/ped#2

**Comment by Toh-HongFeng** [comment]
can remove
