### ISSUE TITLE
[PE-D][Tester B] Identical expenses allowed in one category

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-3/tp#77]
Allowance for event of the same name in one category

![image.png](https://raw.githubusercontent.com/jingyaaa/ped/main/files/17d04bb9-5075-4fd9-8146-cb1f1721d77c.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jingyaaa/ped#5

**Comment by Mnsd05** [comment]
We allow the identical expenses
